/**
 * Swift/iOS Enhancement Pack(决策③,2026-07-11 用户裁定"立项,小步先行")
 * 条件: { languages: ['swift', 'objectivec'] } — 刻意不带 frameworks:
 * iOS 项目无 package.json 式框架清单,detectFrameworks 对 SPM/Xcode 项目只产
 * languages;无框架条件 → resolve('swift', []) 即命中,覆盖全部 iOS 项目。
 *
 * 小步先行:首批 5 条高精度 guard 规则(强转/强 try/IUO 声明/主线程 sync 死锁/
 * Timer target 循环引用),观察一轮误报率后再扩。维度贡献(getExtraDimensions)
 * 一并定义,但 TierScheduler 消费仍未接线(决策②:并入本包立项时设计,登记待接)。
 */

import { type AstSummary, type DetectedPattern, EnhancementPack } from './EnhancementPack.js';

class SwiftIOSEnhancement extends EnhancementPack {
  get id() {
    return 'swift-ios';
  }
  get displayName() {
    return 'Swift / iOS Enhancement';
  }
  get conditions() {
    return { languages: ['swift', 'objectivec'] };
  }

  getExtraDimensions() {
    return [
      {
        id: 'swift-ios-lifecycle-scan',
        label: 'iOS 生命周期与内存分析',
        guide:
          'iOS 生命周期与内存管理分析 — ViewController/View 生命周期钩子使用、weak/unowned 捕获规范、Timer/NotificationCenter/KVO 的注册-注销配对、deinit 清理完整性',
        tierHint: 2,
        knowledgeTypes: ['architecture', 'code-pattern'],
        skillWorthy: true,
        dualOutput: true,
        skillMeta: {
          name: 'project-swift-ios-lifecycle',
          description:
            'iOS lifecycle hooks, retain-cycle avoidance and cleanup pairing patterns (auto-generated by enhancement)',
        },
      },
      {
        id: 'swift-ios-concurrency-scan',
        label: 'Swift 并发与主线程纪律',
        guide:
          'Swift 并发纪律分析 — 主线程 UI 更新路径、GCD 队列使用形态、async/await 与 GCD 混用边界、@MainActor 标注覆盖',
        tierHint: 2,
        knowledgeTypes: ['code-pattern'],
        skillWorthy: true,
        dualOutput: true,
        skillMeta: {
          name: 'project-swift-concurrency',
          description:
            'Swift concurrency discipline: main-thread UI, GCD queue shapes, actor annotations (auto-generated by enhancement)',
        },
      },
    ];
  }

  getGuardRules() {
    // 真机复核(BiliDili HTTP guard):内置规则集已有 swift-force-cast/swift-force-try/
    // main-thread-sync-swift 三条同语义——包规则与之双报是噪音。小步先行收敛:
    // 只保留内置没有的形态;后续扩充前先对照内置集查重。
    return [
      {
        ruleId: 'swift-ios-iuo-property',
        category: 'safety',
        dimension: 'file',
        severity: 'info',
        languages: ['swift'],
        // 隐式解包可选型属性声明(var x: Type!):IBOutlet 之外多为债务形态。
        pattern: /\b(?:var|let)\s+\w+\s*:\s*[A-Z]\w*(?:<[^>\n]{0,80}>)?!/,
        message:
          '隐式解包可选型(Type!)属性在未初始化访问时崩溃——IBOutlet 之外优先明确 Optional 或延迟初始化(lazy)',
      },
      {
        ruleId: 'swift-ios-timer-target-retain',
        category: 'memory',
        dimension: 'file',
        severity: 'warning',
        languages: ['swift'],
        pattern: /Timer\.scheduledTimer\([^)\n]{0,200}target:\s*self\b/,
        message:
          'Timer target: self 强持有目标形成循环引用(invalidate 前不释放)——优先 block 版 API + [weak self],并在 deinit/viewDidDisappear 配对 invalidate',
      },
    ];
  }

  detectPatterns(_astSummary: AstSummary): DetectedPattern[] {
    // 小步先行:首期不做 AST 模式检测(规则面先验证误报率),后续按需扩。
    return [];
  }
}

export const pack = new SwiftIOSEnhancement();
