export type {
  DeprecateVerdict,
  RelevanceVerdict,
  RiskTier,
  UpdateVerdict,
} from './domain/evolution/EvolutionPolicy.js';
// EvolutionPolicy 是 evolution 稳定 facade 的领域决策入口；外层不应继续 deep import domain/evolution。
export { EvolutionPolicy } from './domain/evolution/EvolutionPolicy.js';
export type {
  CandidateForConsolidation,
  ConsolidationAction,
  ConsolidationAdvice,
  CurrentGitHeadBaselineProviderOptions,
  DecayScoreResult,
  DecaySignal,
  DecayStrategy,
  DiffImpactResult,
  DiffInput,
  EnhancementSuggestion,
  EnhancementType,
  EnsureGitDiffCheckpointInput,
  EnsureGitDiffCheckpointResult,
  EvolutionAction,
  EvolutionAuditRecipe,
  EvolutionCandidate,
  EvolutionCandidatePlan,
  EvolutionCandidateReason,
  EvolutionDecision,
  EvolutionResult,
  GitDiffCheckpointBaselineProvider,
  GitDiffCheckpointInitializationSource,
  GitDiffCheckpointRecord,
  GitDiffCheckpointRouteStatus,
  GitDiffCheckpointScope,
  IgnoredChange,
  MergeDirection,
  ProposalExecutionResult,
  RecipeTokens,
  RecordGitDiffCheckpointRouteInput,
  RecordGitDiffCheckpointRouteResult,
  RedundancyResult,
  RescanImpactSubmissionResult,
  StagingCheckResult,
  StagingEntry,
} from './service/sustain/index.js';
export {
  assessDiffImpact,
  assessFileImpact,
  assessImpactUnified,
  ConsolidationAdvisor,
  ContentPatcher,
  CurrentGitHeadBaselineProvider,
  createCurrentGitHeadBaselineProvider,
  DecayDetector,
  EnhancementSuggester,
  ProposalGateway,
  extractApiTokens,
  extractRecipeTokens,
  GitDiffCheckpointService,
  LifecycleStateMachine,
  ProposalExecutor,
  RecipeImpactPlanner,
  RedundancyAnalyzer,
  StagingManager,
  submitRescanImpactDecisions,
  toEvolutionAuditRecipe,
  tokenizeIdentifiers,
  toRescanImpactDecision,
} from './service/sustain/index.js';
