export type {
  CandidateForConsolidation,
  ConsolidationAction,
  ConsolidationAdvice,
  DecayScoreResult,
  DecaySignal,
  DecayStrategy,
  DiffImpactResult,
  DiffInput,
  EnhancementSuggestion,
  EnhancementType,
  EvolutionAction,
  EvolutionAuditRecipe,
  EvolutionCandidate,
  EvolutionCandidatePlan,
  EvolutionCandidateReason,
  EvolutionDecision,
  EvolutionResult,
  IgnoredChange,
  MergeDirection,
  ProposalExecutionResult,
  RecipeTokens,
  RedundancyResult,
  RescanImpactSubmissionResult,
  StagingCheckResult,
  StagingEntry,
} from './service/evolution/index.js';
export {
  assessDiffImpact,
  assessFileImpact,
  assessImpactUnified,
  ConsolidationAdvisor,
  ContentPatcher,
  DecayDetector,
  EnhancementSuggester,
  EvolutionGateway,
  extractApiTokens,
  extractRecipeTokens,
  LifecycleStateMachine,
  ProposalExecutor,
  RecipeImpactPlanner,
  RedundancyAnalyzer,
  StagingManager,
  submitRescanImpactDecisions,
  toEvolutionAuditRecipe,
  tokenizeIdentifiers,
  toRescanImpactDecision,
} from './service/evolution/index.js';
