export {
  FieldLevel,
  getAgentAdapterFieldSpec,
  getAllRequiredFieldNames,
  getExpectedFieldNames,
  getExternalAgentRequiredFields,
  getFieldDef,
  getFieldsByLevel,
  getInternalAgentRequiredFields,
  getRequiredFieldNames,
  getRequiredFieldsDescription,
  getSystemInjectedFields,
  STANDARD_CATEGORIES,
  V3_FIELD_SPEC,
  VALID_KINDS,
  VALID_TOPIC_HINTS,
  WHITELISTED_CATEGORIES,
} from './domain/knowledge/FieldSpec.js';
export {
  CANDIDATE_LIFECYCLES,
  CANDIDATE_STATES,
  CONSUMABLE_LIFECYCLES,
  CONSUMABLE_STATES,
  COUNTABLE_LIFECYCLES,
  DEGRADED_STATES,
  GUARD_LIFECYCLES,
  inferKind,
  isCandidate,
  isConsumable,
  isDegraded,
  isValidLifecycle,
  isValidTransition,
  KnowledgeEntry,
  KnowledgeRepository,
  Lifecycle,
  lifecycleInSql,
  NON_DEPRECATED_LIFECYCLES,
  normalizeLifecycle,
  PUBLISHED_LIFECYCLES,
} from './domain/knowledge/index.js';
export type { KnowledgeEntryProps } from './domain/knowledge/KnowledgeEntry.js';
export type {
  DepthDimension,
  DepthReviewInput,
  DepthReviewResult,
  DocScoreTargets,
  FailureMode,
  GateRule,
  GuidanceBlock,
  RecipeAuthoringProfile,
  RecipeAuthoringSubmitPath,
  RecipeAuthoringViolation,
  RecipeSessionScope,
  RecipeSourceRefEvidence,
  RecipeSourceRefResolver,
  Stage3FieldPolicy,
  SubmissionSpec,
  SubmitContract,
  ValidateAgainstOptions,
  WorkedExample,
} from './domain/knowledge/recipe-authoring-spec/index.js';
// RecipeAuthoringSpec — Recipe 创作权威规范的 A.3 公共 API。
// 门禁 validateAgainst 与指南 renderGuidance 读取同一 gateRules() 表（guidance==gate 的结构性保证）。
// 仅在此导出 NEW 符号；V3_FIELD_SPEC 等 FieldSpec getters 已由上方 FieldSpec 块导出，避免同名重复导出。
export {
  applyStyleWaiver,
  buildDepthScaffold,
  buildDepthSelfReviewChecklist,
  buildPreSubmitChecklist,
  buildSubmissionSpec,
  buildSubmitKnowledgeContract,
  contentContract,
  DEPTH_DIMENSIONS,
  DIMENSION_COMPLETION_FLOOR,
  describeSubmitToolFields,
  example,
  failureModes,
  gateRule,
  gateRules,
  getEvidenceFloorPolicy,
  getImperativeVerbAllowlist,
  getStage3FieldPolicy,
  isSoftAuthoringViolation,
  RECIPE_PIPELINE_EVENTS,
  RELATIONSHIP_CN_RE,
  RELATIONSHIP_EN_RE,
  renderGuidance,
  resolveAuthoringProfile,
  resolveGroundedSourcePaths,
  reviewRecipeDepth,
  STYLE_WAIVER_MIN_JUSTIFICATION,
  STYLE_WAIVER_SESSION_LIMIT,
  VALUE_RUBRIC,
  validateAgainst,
} from './domain/knowledge/recipe-authoring-spec/index.js';
// W2(2026-07-02):生成链事件 payload 基础契约(与 RECIPE_PIPELINE_EVENTS 同域单源)。
export type {
  DimensionCheckpointRestoredPayload,
  DimensionCompletePayload,
  DimensionErrorPayload,
  DimensionHostAgentCompletePayload,
  DimensionHostCompletePayload,
  DimensionPipelineCompletePayload,
  DimensionRestoredPayload,
  DimensionSkillPayload,
  DimensionSkippedPayload,
  ProgressPayload,
} from './domain/knowledge/recipe-authoring-spec/pipelineEventPayloads.js';
export {
  buildProducerStyleGuide,
  SUBMIT_REQUIREMENTS,
} from './domain/knowledge/StyleGuide.js';
export {
  createStatelessValidator,
  UnifiedValidator,
} from './domain/knowledge/UnifiedValidator.js';
export {
  Constraints,
  Content,
  Quality,
  RELATION_BUCKETS,
  Reasoning,
  Relations,
  Stats,
} from './domain/knowledge/values/index.js';
export type {
  KnowledgeFileScanner,
  KnowledgeFileStore,
} from './repository/knowledge/KnowledgeFileStore.js';
export type {
  RecipeSourceRefEntity,
  RecipeSourceRefInsert,
} from './repository/sourceref/RecipeSourceRefRepository.js';
// CO2 B3: unified validator entry — composes UnifiedValidator + RecipeCandidateValidator +
// CandidateAggregator so callers cannot accidentally pick a weaker subset. No enforcement.
export {
  type UnifiedCandidateValidationItem,
  type UnifiedCandidateValidationOptions,
  type UnifiedCandidateValidationResult,
  validateCandidatesUnified,
} from './service/candidate/CandidateValidationFacade.js';
// P5/C8: 可复用 fs-backed 源码引用解析器——两宿主注入 KnowledgeService 的 groundedSourcePaths port 时共用，
// 保证深度接地判定 parity（Core 拥有共享 fs 能力，domain spec 仍 fs-free）。
export { createFsSourceRefResolver } from './service/knowledge/FsSourceRefResolver.js';
export {
  type ApplyReport,
  type BlockedRecipeInfo,
  CodeEntityGraph,
  ConfidenceRouter,
  type CreatedRecipeInfo,
  type CreateRecipeItem,
  type CreateRecipeRequest,
  type CreateRecipeResult,
  computeKnowledgeHash,
  type GatewayDeps,
  type GatewaySource,
  getGatewaySourceLabel,
  getGatewaySourceUserId,
  getKnowledgeGraphService,
  initKnowledgeGraphService,
  KnowledgeFileWriter,
  KnowledgeGraphService,
  KnowledgeService,
  KnowledgeSyncService,
  type MergedRecipeInfo,
  normalizeGatewaySource,
  type PathRename,
  parseKnowledgeMarkdown,
  RecipeExtractor,
  type RecipeFreshnessEntry,
  type RecipeFreshnessRecipeResult,
  type RecipeFreshnessRefreshResult,
  RecipeFreshnessService,
  type RecipeFreshnessServiceDeps,
  type RecipeFreshnessSourceRefSummary,
  type RecipeFreshnessVectorService,
  type RecipeFreshnessVectorSummary,
  RecipeProductionGateway,
  type ReconcileRecipeSourceRefsInput,
  type ReconcileReport,
  type RejectedRecipeInfo,
  RelationType,
  type RepairReport,
  type RewriteResult,
  rewriteRecipePaths,
  type SimilarRecipeInfo,
  SourceRefReconciler,
  type SyncAllReport,
} from './service/knowledge/index.js';
