// 证据台账契约（Wave A E1）：冷启动证据保真——引用=台账条目 ID，file:line 由条目机械展开。
// 纯领域契约；存储实现在宿主运行时（AlembicAgent），提交门禁语义不因台账放松。

export {
  EVIDENCE_ENTRY_MAX_CHARS,
  EVIDENCE_ID_RE,
  EVIDENCE_TOOL_IDS,
  type EvidenceEntry,
  type EvidenceRange,
  type EvidenceToolId,
  isEvidenceToolId,
  isValidEvidenceEntry,
  makeEvidenceId,
  type ParsedEvidenceRef,
  parseEvidenceRef,
} from './domain/knowledge/evidence-ledger/index.js';
export {
  FieldLevel,
  getAgentAdapterFieldSpec,
  getAllRequiredFieldNames,
  getExpectedFieldNames,
  getExternalAgentRequiredFields,
  getFieldDef,
  getFieldsByLevel,
  getInternalAgentRequiredFields,
  getRequiredFieldNames,
  getRequiredFieldsDescription,
  getSystemInjectedFields,
  STANDARD_CATEGORIES,
  V3_FIELD_SPEC,
  VALID_KINDS,
  VALID_TOPIC_HINTS,
  WHITELISTED_CATEGORIES,
} from './domain/knowledge/FieldSpec.js';
export {
  CANDIDATE_LIFECYCLES,
  CANDIDATE_STATES,
  CONSUMABLE_LIFECYCLES,
  CONSUMABLE_STATES,
  COUNTABLE_LIFECYCLES,
  DEGRADED_STATES,
  GUARD_LIFECYCLES,
  inferKind,
  isCandidate,
  isConsumable,
  isDegraded,
  isValidLifecycle,
  isValidTransition,
  KnowledgeEntry,
  KnowledgeRepository,
  Lifecycle,
  lifecycleInSql,
  NON_DEPRECATED_LIFECYCLES,
  normalizeLifecycle,
  PUBLISHED_LIFECYCLES,
} from './domain/knowledge/index.js';
export type { KnowledgeEntryProps } from './domain/knowledge/KnowledgeEntry.js';
export type {
  RecipeRetrievalFact,
  RecipeRetrievalProfile,
  RecipeRetrievalProvenance,
  RecipeRetrievalSummary,
} from './domain/knowledge/RecipeRetrievalProfile.js';
export type {
  DepthDimension,
  DepthReviewInput,
  DepthReviewResult,
  DocScoreTargets,
  FailureMode,
  GateRule,
  GuidanceBlock,
  RecipeAuthoringProfile,
  RecipeAuthoringSubmitPath,
  RecipeAuthoringViolation,
  RecipeSessionScope,
  RecipeSourceRefEvidence,
  RecipeSourceRefResolver,
  Stage3FieldPolicy,
  SubmissionSpec,
  SubmitContract,
  ValidateAgainstOptions,
  WorkedExample,
} from './domain/knowledge/recipe-authoring-spec/index.js';
// RecipeAuthoringSpec — Recipe 创作权威规范的 A.3 公共 API。
// 门禁 validateAgainst 与指南 renderGuidance 读取同一 gateRules() 表（guidance==gate 的结构性保证）。
// 仅在此导出 NEW 符号；V3_FIELD_SPEC 等 FieldSpec getters 已由上方 FieldSpec 块导出，避免同名重复导出。
export {
  applyStyleWaiver,
  buildDepthScaffold,
  buildDepthSelfReviewChecklist,
  buildPreSubmitChecklist,
  buildSubmissionSpec,
  buildSubmitKnowledgeContract,
  contentContract,
  DEPTH_DIMENSIONS,
  DIMENSION_COMPLETION_FLOOR,
  describeSubmitToolFields,
  example,
  failureModes,
  gateRule,
  gateRules,
  getEvidenceFloorPolicy,
  getImperativeVerbAllowlist,
  getStage3FieldPolicy,
  isSoftAuthoringViolation,
  RECIPE_PIPELINE_EVENTS,
  RELATIONSHIP_CN_RE,
  RELATIONSHIP_EN_RE,
  renderGuidance,
  resolveAuthoringProfile,
  resolveGroundedSourcePaths,
  reviewRecipeDepth,
  STYLE_WAIVER_MIN_JUSTIFICATION,
  STYLE_WAIVER_SESSION_LIMIT,
  VALUE_RUBRIC,
  validateAgainst,
} from './domain/knowledge/recipe-authoring-spec/index.js';
// W2(2026-07-02):生成链事件 payload 基础契约(与 RECIPE_PIPELINE_EVENTS 同域单源)。
export type {
  DimensionCheckpointRestoredPayload,
  DimensionCompletePayload,
  DimensionErrorPayload,
  DimensionHostAgentCompletePayload,
  DimensionHostCompletePayload,
  DimensionPipelineCompletePayload,
  DimensionRestoredPayload,
  DimensionSkillPayload,
  DimensionSkippedPayload,
  ProgressPayload,
} from './domain/knowledge/recipe-authoring-spec/pipelineEventPayloads.js';
export {
  buildProducerStyleGuide,
  SUBMIT_REQUIREMENTS,
} from './domain/knowledge/StyleGuide.js';
export {
  createStatelessValidator,
  UnifiedValidator,
} from './domain/knowledge/UnifiedValidator.js';
export {
  Constraints,
  Content,
  Quality,
  RELATION_BUCKETS,
  Reasoning,
  Relations,
  Stats,
} from './domain/knowledge/values/index.js';
export type {
  KnowledgeFileScanner,
  KnowledgeFileStore,
} from './repository/knowledge/KnowledgeFileStore.js';
export type {
  RecipeSourceRefEntity,
  RecipeSourceRefInsert,
} from './repository/sourceref/RecipeSourceRefRepository.js';
// P5/C8: 可复用 fs-backed 源码引用解析器——两宿主注入 KnowledgeService 的 groundedSourcePaths port 时共用，
// 保证深度接地判定 parity（Core 拥有共享 fs 能力，domain spec 仍 fs-free）。
export { createFsSourceRefResolver } from './service/knowledge/FsSourceRefResolver.js';
export {
  type ApplyReport,
  type BlockedRecipeInfo,
  CodeEntityGraph,
  ConfidenceRouter,
  type CreatedRecipeInfo,
  type CreateRecipeItem,
  type CreateRecipeRequest,
  type CreateRecipeResult,
  computeKnowledgeHash,
  // P-B/P-C(2026-07-11 落锚 parity):主体挖掘钩子与 drift 基线助手消费的
  // 指纹/区间/路径剥离三件套(与 reconciler 落锚口径同源)。
  computeSourceRegionFingerprint,
  createStrictRecipePersistedPayloadV1,
  type GatewayDeps,
  type GatewaySource,
  getGatewaySourceLabel,
  getGatewaySourceUserId,
  getKnowledgeGraphService,
  initKnowledgeGraphService,
  KnowledgeFileWriter,
  KnowledgeGraphService,
  KnowledgeService,
  KnowledgeSyncService,
  type KnowledgeVectorMaintenance,
  type MergedRecipeInfo,
  normalizeGatewaySource,
  type PathRename,
  type PreparedRecipeInspectionV1,
  type ProducerContext,
  type PublishContext,
  parseKnowledgeMarkdown,
  parseSourceLineRange,
  RecipeExtractor,
  type RecipeFreshnessEntry,
  type RecipeFreshnessRecipeResult,
  type RecipeFreshnessRefreshResult,
  RecipeFreshnessService,
  type RecipeFreshnessServiceDeps,
  type RecipeFreshnessSourceRefSummary,
  type RecipeFreshnessVectorService,
  type RecipeFreshnessVectorSummary,
  type RecipeProducerCapability,
  type RecipeProductionEvidence,
  RecipeProductionGateway,
  type RecipeProductionInput,
  type RecipeProductionPort,
  type RecipeProductionRecord,
  type RecipeProductionResult,
  type RecipeProductionSource,
  type ReconcileRecipeSourceRefsInput,
  type ReconcileReport,
  type RejectedRecipeInfo,
  RelationType,
  type RepairReport,
  type RewriteResult,
  rewriteRecipePaths,
  type SimilarRecipeInfo,
  SourceRefReconciler,
  type StrictCandidateAdmissionContextV1,
  type StrictCandidateAdmissionResultV1,
  type StrictPreparedRecipePersistenceContextV1,
  type StrictPreparedRecipePersistencePortV1,
  type StrictPreparedRecipePersistenceResultV1,
  type SyncAllReport,
  stripSourceRangeSuffix,
} from './service/knowledge/index.js';
// CO2 B3: unified validator entry — composes UnifiedValidator + RecipeCandidateValidator +
// CandidateAggregator so callers cannot accidentally pick a weaker subset. No enforcement.
export {
  type UnifiedCandidateValidationItem,
  type UnifiedCandidateValidationOptions,
  type UnifiedCandidateValidationResult,
  validateCandidatesUnified,
} from './service/knowledge/validation/candidate/CandidateValidationFacade.js';
export {
  assertStrictAcceptedCorpusInspectionV1,
  assertStrictAdmissionReceiptV1,
  assertStrictG1ReceiptV1,
  assertStrictG2ReceiptV1,
  assertStrictPersistenceAuthorityV1,
  type CandidateAttemptBatchV1,
  type CandidateAttemptInputV1,
  type CandidateCoverageCellV1,
  type CandidateCoverageDisposition,
  type CandidateCoverageReceiptV1,
  canonicalizeCandidateAttemptBatchV1,
  classifyPublicKnowledgeRouteRecoveryV1,
  createCandidateCoverageReceiptV1,
  createFinalCoverageBindingReceiptV1,
  createRecipeCandidateFingerprintProjectionV1,
  createRecipeProductionBindingV1,
  createRefReconciliationReceiptV1,
  createServingSnapshotManifestV1,
  createStrictAcceptedCorpusInspectionV1,
  createStrictAdmissionReceiptV1,
  createStrictG1ReceiptV1,
  createStrictG2ReceiptV1,
  createStrictPersistenceReceiptV1,
  createStrictPublicationMarkerV1,
  createStrictPublicationSnapshotIdV1,
  type FinalCoverageBindingReceiptV1,
  type FinalCoverageDisposition,
  type PreparedPublicKnowledgeRouteV1,
  type PreparedRecipePersistenceV1,
  type PublicKnowledgeRouteRecoveryDecisionV1,
  type PublicKnowledgeRouteV1,
  parseStrictPublicationSnapshotIdV1,
  preparePublicKnowledgeRouteV1,
  prepareRecipePersistenceV1,
  type RecipeCandidateFingerprintProjectionV1,
  type RecipeProductionBindingV1,
  type RefReconciliationReceiptV1,
  type SerialAdmissionLedgerV1,
  type SerialAdmissionRowV1,
  type ServingSnapshotManifestV1,
  STRICT_G1_HARD_AXES_V1,
  STRICT_G2_HARD_AXES_V1,
  type StrictAcceptedCorpusEntryV1,
  type StrictAcceptedCorpusInspectionV1,
  type StrictAcceptedRecipeAdmissionSummaryV1,
  type StrictAdmissionConsolidationV1,
  type StrictAdmissionExactMatchV1,
  type StrictAdmissionReceiptV1,
  type StrictAdmissionSemanticMatchV1,
  type StrictG1AxisResultV1,
  type StrictG1HardAxisV1,
  type StrictG1ReceiptV1,
  type StrictG2ActorV1,
  type StrictG2AxisResultV1,
  type StrictG2DuplicateDecisionV1,
  type StrictG2HardAxisV1,
  type StrictG2NoveltyDecisionV1,
  type StrictG2ReceiptV1,
  type StrictPersistenceReceiptV1,
  type StrictPublicationMarkerV1,
  type StrictPublicationSnapshotIdV1,
  validateSerialAdmissionLedgerV1,
} from './service/production/ProductionPersistenceContracts.js';
