export type {
  AnchorRangeContext,
  AnchorRangeRadius,
  FileFlowContext,
  FileSymbolContext,
  HotspotSummary,
  ModuleContext,
  ModuleLayerContext,
  ProjectContext as ProjectContextContract,
  ProjectContextAnchor,
  ProjectContextEnvelope,
  ProjectContextLevel,
  ProjectContextPresenterInput,
  ProjectContextPresenterUnavailable,
  ProjectContextPresenterWarning,
  ProjectContextProject,
  ProjectContextQueryError,
  ProjectContextQueryErrorCode,
  ProjectContextRef,
  ProjectContextRefKind,
  ProjectContextRequest,
  ProjectContextRequestKind,
  ProjectContextResult,
  ProjectContextScopeInput,
  ProjectMap,
  ProjectMapSummary,
  RepoContext,
  SourceSliceContext,
  SpaceContext,
} from './domain/project-context/index.js';
export { buildProjectContextPresenterInput } from './domain/project-context/index.js';
export type {
  ArchitectureCodeEntitySnapshot,
  ArchitectureDimensionCoverageSnapshot,
  ArchitectureDomain,
  ArchitectureEvidence,
  ArchitectureEvidenceSource,
  ArchitectureGraphModuleSnapshot,
  ArchitectureGraphSnapshot,
  ArchitectureIntelligenceInput,
  ArchitectureIntelligenceReport,
  ArchitectureKnowledgeEdgeSnapshot,
  ArchitectureManifestDependency,
  ArchitectureStyle,
  ArchitectureStyleReport,
  CallFlowAggregateReport,
  ComplexityReport,
  CouplingAnalysisReport,
  DomainSignal,
  DomainSignalReport,
  HealthGap,
  ProjectContextCapabilities as ProjectContextCapabilitiesContract,
  ProjectContextCapabilityQuery,
  ProjectInformationSupplementReport,
  RefinedModuleRole,
} from './project-context-capabilities.js';
export {
  createProjectContextCapabilities,
  ProjectContextCapabilities,
} from './project-context-capabilities.js';
export { ProjectContext } from './service/project-context/ProjectContextService.js';
