// 解析语言单源(2026-07-11 P-D D6):Plugin 图适配层的 file-flow 目标选择消费同一
// 扩展名词表(此前它持第 6 份 JS-only 私有白名单,.swift 在选择层即被丢弃)。
export {
  AST_PARSER_LANGUAGES,
  EXTENSION_PARSER_LANGUAGE,
  JS_FAMILY_LANGUAGES,
  resolveAstParserLanguage,
} from './core/facts/parserLanguage.js';
export type {
  AnchorRangeContext,
  AnchorRangeRadius,
  FileFlowContext,
  FileSummary,
  FileSymbolContext,
  HotspotSummary,
  ModuleContext,
  ModuleLayerContext,
  ModuleSummary,
  ParsedProjectContextRef,
  ParsedRelationGraphRef,
  ProjectContext as ProjectContextContract,
  ProjectContextAnchor,
  ProjectContextEnvelope,
  ProjectContextExecutionContext,
  ProjectContextLevel,
  ProjectContextPresenterInput,
  ProjectContextPresenterUnavailable,
  ProjectContextPresenterWarning,
  ProjectContextProject,
  ProjectContextQueryError,
  ProjectContextQueryErrorCode,
  ProjectContextRef,
  ProjectContextRefKind,
  ProjectContextRequest,
  ProjectContextRequestKind,
  ProjectContextResult,
  ProjectContextScopeInput,
  ProjectEvidenceContext,
  ProjectImpactContext,
  ProjectIndexState,
  ProjectMap,
  ProjectMapSummary,
  ProjectModuleDependencyContext,
  ProjectModuleDependencySummary,
  ProjectRelationEnvelope,
  ProjectRelationKind,
  ProjectRelationRequest,
  ProjectRelationResult,
  ProjectRelationTarget,
  ProjectRelationUnavailableContext,
  ProjectRelationWalkContext,
  ProjectRelationWalkKind,
  ProjectSymbolListContext,
  RelationResolutionSummary,
  RelationSummary,
  RepoContext,
  SourceSliceContext,
  SpaceContext,
  SymbolSummary,
} from './domain/project-context/index.js';
export {
  buildProjectContextPresenterInput,
  formatRelationGraphRef,
  isProjectRelationKind,
  isStructuredGraphRef,
  PROJECT_RELATION_KIND_VALUES,
  parseProjectContextRef,
  parseRelationGraphRef,
} from './domain/project-context/index.js';
export type {
  ArchitectureCodeEntitySnapshot,
  ArchitectureDimensionCoverageSnapshot,
  ArchitectureDomain,
  ArchitectureEvidence,
  ArchitectureEvidenceSource,
  ArchitectureGraphModuleSnapshot,
  ArchitectureGraphSnapshot,
  ArchitectureIntelligenceInput,
  ArchitectureIntelligenceReport,
  ArchitectureKnowledgeEdgeSnapshot,
  ArchitectureManifestDependency,
  ArchitectureStyle,
  ArchitectureStyleReport,
  ComplexityReport,
  DomainSignal,
  DomainSignalReport,
  ProjectContextCapabilities as ProjectContextCapabilitiesContract,
  ProjectContextCapabilityQuery,
  ProjectInformationSupplementReport,
} from './project-context-capabilities.js';
export {
  createProjectContextCapabilities,
  ProjectContextCapabilities,
} from './project-context-capabilities.js';
export {
  type CodeGraphProjectContextOptions,
  type CodeGraphProjectContextRuntime,
  getCodeGraphProjectContextIdentity,
  withCodeGraphProjectContextSession,
} from './service/project-context/analysis/codeGraphSession.js';
export {
  ProjectContext,
  withProjectContextSession,
} from './service/project-context/ProjectContextService.js';
// 关系查询（跨文件、可反向）：回答来自源码索引，用的是协议自己的符号与引用。
export {
  createProjectRelations,
  type ProjectRelations,
  type ProjectRelationsOptions,
} from './service/project-context/relations/index.js';
// PC-F final-artifact 合约冻结 foundation 聚合面；文件引用 helper 属于 live ProjectContext 公共能力。
export { createProjectContextFileRef } from './service/project-context/shared/sourceSlice-fileSymbols/contracts.js';
