export type {
  DeprecateVerdict,
  RelevanceVerdict,
  RiskTier,
  UpdateVerdict,
} from './domain/evolution/EvolutionPolicy.js';
// EvolutionPolicy 是 sustain 稳定 facade 的领域决策入口(进化决策机制词保留);外层不应 deep import domain/evolution。
export { EvolutionPolicy } from './domain/evolution/EvolutionPolicy.js';
// 相似度 port 具名导出(W3):此前外层只能从 RedundancyAnalyzer ctor 结构化派生(Plugin recipe-embedding-sim-provider 欠账)。
export type {
  EmbeddingSimProvider,
  SimilarityRecipeLike,
} from './domain/similarity/RecipeSimilarity.js';
export type {
  BuildGitDiffCheckpointScopeInput,
  CandidateForConsolidation,
  ConsolidationAction,
  ConsolidationAdvice,
  CurrentGitHeadBaselineProviderOptions,
  DecayScoreResult,
  DecaySignal,
  DecayStrategy,
  DiffImpactResult,
  DiffInput,
  EnhancementSuggestion,
  EnhancementType,
  EnsureGitDiffCheckpointInput,
  EnsureGitDiffCheckpointResult,
  EvolutionAction,
  EvolutionAuditRecipe,
  EvolutionCandidate,
  EvolutionCandidatePlan,
  EvolutionCandidateReason,
  EvolutionDecision,
  EvolutionResult,
  GitDiffCheckpointBaselineProvider,
  GitDiffCheckpointInitializationSource,
  GitDiffCheckpointRecord,
  GitDiffCheckpointRouteStatus,
  GitDiffCheckpointScope,
  IgnoredChange,
  MergeDirection,
  ProposalExecutionResult,
  RecipeTokens,
  RecordGitDiffCheckpointRouteInput,
  RecordGitDiffCheckpointRouteResult,
  RedundancyResult,
  RescanImpactSubmissionResult,
  StagingCheckResult,
  StagingEntry,
} from './service/sustain/index.js';
export {
  assessDiffImpact,
  assessFileImpact,
  assessImpactUnified,
  // checkpoint scope 归一单源(2026-07-11 下沉):双宿主读写 git_diff_checkpoints 必须同键。
  buildGitDiffCheckpointScope,
  ConsolidationAdvisor,
  ContentPatcher,
  CurrentGitHeadBaselineProvider,
  createCurrentGitHeadBaselineProvider,
  DecayDetector,
  EnhancementSuggester,
  extractApiTokens,
  extractRecipeTokens,
  GitDiffCheckpointService,
  LifecycleStateMachine,
  ProposalExecutor,
  ProposalGateway,
  RecipeImpactPlanner,
  RedundancyAnalyzer,
  StagingManager,
  submitRescanImpactDecisions,
  toEvolutionAuditRecipe,
  tokenizeIdentifiers,
  toRescanImpactDecision,
} from './service/sustain/index.js';
